workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare Flutter & CocoaPods
        script: |
          set -euxo pipefail
          flutter --version
          flutter pub get
          # iOS-Gerüst sicherstellen
          flutter create . --platforms=ios
          # CocoaPods vorbereiten (iOS 13+)
          cd ios
          sed -i.bak -e "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || true
          pod repo update
          pod install
          cd ..

      - name: Build iOS (try Release, else Debug) ohne Codesign
        script: |
          set -euxo pipefail
          flutter clean
          # Versuch 1: Release ohne Codesign
          if ! flutter build ios --release --no-codesign; then
            echo "Release-Build ohne Codesign fehlgeschlagen – versuche Debug…"
            flutter clean
            flutter build ios --debug --no-codesign
          fi
          echo "Suche nach Runner.app…"
          find build -type d -name "Runner.app" -print || true

      - name: Package unsigned IPA
        script: |
          set -euxo pipefail
          APP_PATH="$(find build -type d -name 'Runner.app' | head -n 1)"
          if [ -z "$APP_PATH" ]; then
            echo "Runner.app nicht gefunden. Abbruch."
            exit 1
          fi
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Fertige Artefakte:"
          ls -la out

    artifacts:
      - out/*.ipa
