workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare Flutter
        script: |
          flutter --version
          flutter pub get
          # falls ios/ noch fehlt:
          flutter create . --platforms=ios

      - name: CocoaPods installieren/aktualisieren
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: (Info) Xcode Schemes anzeigen
        script: |
          xcodebuild -list -workspace ios/Runner.xcworkspace || true

      - name: Build .app via xcodebuild (ohne Codesign)
        script: |
          set -euxo pipefail
          xcodebuild -version
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/ios_nosign \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            build

          APP_PATH="build/ios_nosign/Build/Products/Release-iphoneos/Runner.app"
          echo "Erzeugte App:"
          ls -la "$APP_PATH"

      - name: Package unsigned IPA
        script: |
          set -euxo pipefail
          APP_PATH="build/ios_nosign/Build/Products/Release-iphoneos/Runner.app"
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Finale Artefakte:"
          ls -la out

    artifacts:
      - out/*.ipa
