workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare Flutter
        script: |
          flutter --version
          flutter pub get
          # falls ios/ noch fehlt:
          flutter create . --platforms=ios

      - name: Build archive (no codesign)
        script: |
          set -e
          flutter clean
          # Baut ein .xcarchive ohne Signatur (kein Team nötig)
          flutter build ipa --release --no-codesign
          echo "Archive tree:"
          ls -R build/ios/archive || true

      - name: Package unsigned IPA from .xcarchive
        script: |
          set -e
          APP_PATH="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app nicht gefunden. Verfügbare Runner.app:"
            find build -name "Runner.app" -print
            exit 1
          fi
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Finale Artefakte:"
          ls -la out

    artifacts:
      - out/*.ipa
