workflows:
  ios_signed:
    name: iOS signed (Optimizer)
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore_connect        # <— DIESE ZEILE(n) SIND WICHTIG
      vars:
        BUNDLE_ID: ch.soleco.optimizer
        EXPORT_METHOD: app-store   # oder ad-hoc
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods

    scripts:
      - name: Resolve deps & iOS 13+
        script: |
          flutter --version
          flutter pub get
          cd ios
          sed -i.bak -e "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || true
          cd ..

      - name: Set app name & bundle id (Optimizer)
        script: |
          INFO="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Optimizer" "$INFO" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string Optimizer" "$INFO"
          /usr/libexec/PlistBuddy -c "Set :CFBundleName Optimizer" "$INFO" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleName string Optimizer" "$INFO"
          sed -i.bak -E "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" ios/Runner.xcodeproj/project.pbxproj

      - name: 🔑 Fetch signing files (automatic)
        script: |
          set -euxo pipefail
          # Prüfen, ob die Variablen da sind (zeigt keine Secrets an)
          test -n "${APP_STORE_CONNECT_KEY_IDENTIFIER}" || (echo "Missing APP_STORE_CONNECT_KEY_IDENTIFIER"; exit 1)
          test -n "${APP_STORE_CONNECT_ISSUER_ID}"    || (echo "Missing APP_STORE_CONNECT_ISSUER_ID"; exit 1)
          test -n "${APP_STORE_TEAM_ID}"              || (echo "Missing APP_STORE_TEAM_ID"; exit 1)
          test -n "${APP_STORE_CONNECT_PRIVATE_KEY}"  || (echo "Missing APP_STORE_CONNECT_PRIVATE_KEY"; exit 1)

          keychain initialize
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/appstore_key.p8

          if [ "$EXPORT_METHOD" = "ad-hoc" ]; then
            SIGNING_TYPE="IOS_ADHOC"
          else
            SIGNING_TYPE="IOS_APP_STORE"
          fi

          app-store-connect fetch-signing-files \
            --api-key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --api-issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --api-private-key-file /tmp/appstore_key.p8 \
            --type "$SIGNING_TYPE" \
            --bundle-identifier "$BUNDLE_ID" \
            --create \
            --team-id "$APP_STORE_TEAM_ID"

          keychain add-certificates
          xcode-project use-profiles

      - name: Build signed IPA (Release)
        script: |
          flutter clean
          flutter build ipa --release
          ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
