workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare Flutter
        script: |
          flutter --version
          flutter pub get
          # sicherstellen, dass ios/ vorhanden ist
          flutter create . --platforms=ios

      - name: Build archive with Flutter (no codesign) – tolerate nonzero exit
        script: |
          set +e
          flutter clean
          flutter build ipa --release --no-codesign
          EXIT_CODE=$?
          echo "flutter build ipa exit code: $EXIT_CODE"
          echo "Archive tree:"
          ls -R build/ios/archive || true

          # Prüfen, ob das Archiv existiert – wenn ja, trotzdem OK weiterbauen
          APP_DIR="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_DIR" ]; then
            echo "Runner.app nicht gefunden. Versuche Fallback-Suche..."
            find build -type d -name "Runner.app" -print
            # Wenn weiterhin nichts da: jetzt wirklich fehlschlagen
            if ! find build -type d -name "Runner.app" | grep -q . ; then
              echo "Kein Runner.app im Build gefunden. Abbruch."
              exit 1
            fi
          fi
          # Exit NICHT hart fehlschlagen, selbst wenn EXIT_CODE != 0
          exit 0

      - name: Package unsigned IPA from .xcarchive (or found Runner.app)
        script: |
          set -e
          APP_PATH="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            # Fallback: nimm das erste gefundene Runner.app irgendwo im Build
            APP_PATH="$(find build -type d -name "Runner.app" | head -n 1)"
          fi
          echo "Using app at: $APP_PATH"
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Final artifacts in out/:"
          ls -la out

    artifacts:
      - out/*.ipa
