workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare Flutter & iOS project
        script: |
          set -euxo pipefail
          flutter --version
          flutter pub get
          # iOS-Gerüst sicherstellen
          flutter create . --platforms=ios
          # CocoaPods vorbereiten (iOS 13+)
          cd ios
          sed -i.bak -e "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || true
          pod repo update
          pod install
          cd ..

      - name: Warm up Flutter Xcode configs (ignore exit)
        script: |
          set +e
          # Dieser Schritt erzeugt u. a. Generated.xcconfig, damit xcodebuild später nicht mit Exit 65 stirbt.
          flutter clean
          flutter build ios --debug --no-codesign
          echo "flutter build ios (warm up) exit: $?"
          set -e

      - name: Build .app via xcodebuild (NO codesign)
        script: |
          set -euxo pipefail
          # Wichtige Variablen für Flutter-Build-Phasen
          export FLUTTER_ROOT="$(dirname "$(dirname "$(which flutter)")")"
          export FLUTTER_APPLICATION_PATH="$PWD"
          export FLUTTER_TARGET="lib/main.dart"

          # Nur Gerät (iphoneos), ohne Codesign, Release-Optimierungen
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/ios_nosign \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            build

          echo "Build products:"
          ls -la build/ios_nosign/Build/Products/Release-iphoneos || true

      - name: Package unsigned IPA
        script: |
          set -euxo pipefail
          # Standardpfad des xcodebuild-Outputs
          APP_PATH="build/ios_nosign/Build/Products/Release-iphoneos/Runner.app"

          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app nicht am erwarteten Ort, suche Fallback…"
            APP_PATH="$(find build -type d -name 'Runner.app' | head -n 1 || true)"
          fi

          if [ -z "${APP_PATH:-}" ] || [ ! -d "$APP_PATH" ]; then
            echo "Runner.app nicht gefunden. Verfügbare App-Pfade:"
            find build -type d -name '*.app' -maxdepth 6 -print || true
            exit 1
          fi

          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Fertige Artefakte:"
          ls -la out

    artifacts:
      - out/*.ipa
