workflows:
  ios_signed:
    name: iOS signed (Optimizer)
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods

    scripts:
      - name: Resolve deps & iOS 13+
        script: |
          flutter --version
          flutter pub get
          cd ios
          sed -i.bak -e "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || true
          cd ..

      - name: Set app name & bundle id (ch.soleco.optimizer)
        script: |
          BUNDLE_ID="ch.soleco.optimizer"
          INFO="ios/Runner/Info.plist"

          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Optimizer" "$INFO" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string Optimizer" "$INFO"
          /usr/libexec/PlistBuddy -c "Set :CFBundleName Optimizer" "$INFO" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleName string Optimizer" "$INFO"

          sed -i.bak -E "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Build signed IPA (Release)
        script: |
          flutter clean
          flutter build ipa --release
          echo "IPA(s):"
          ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
