workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Ensure iOS platform exists
        script: flutter create . --platforms=ios

      - name: Build iOS (no codesign)
        script: |
          flutter clean
          flutter build ipa --release --no-codesign
          echo "Listing IPA files:"
          find build/ios/ipa -name "*.ipa" -print

    artifacts:
      - build/ios/ipa/*.ipa
