workflows:
  ios_unsigned:
    name: iOS unsigned IPA
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare Flutter
        script: |
          flutter --version
          flutter pub get
          # sicherstellen, dass ios/ vorhanden ist
          flutter create . --platforms=ios

      - name: CocoaPods aktualisieren
        script: |
          cd ios
          # iOS-Minimum auf 13.0 anheben (falls noch nicht gesetzt)
          sed -i.bak -e "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || true
          pod repo update
          pod install
          cd ..

      - name: Build iOS DEBUG (ohne Codesign)
        script: |
          set -euxo pipefail
          flutter clean
          # Debug-Build erzeugt eine .app für echte Geräte ohne Signierung
          flutter build ios --debug --no-codesign
          echo "Inhalt von build/ios/iphoneos:"
          ls -la build/ios/iphoneos || true

      - name: Package unsigned IPA
        script: |
          set -euxo pipefail
          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            # Fallback: suche Runner.app irgendwo im Build
            APP_PATH="$(find build -type d -name 'Runner.app' | head -n 1)"
          fi
          echo "Verwende App unter: $APP_PATH"
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r SolecoWrapper-unsigned.ipa Payload)
          rm -rf out/Payload
          echo "Finale Artefakte in out/:"
          ls -la out

    artifacts:
      - out/*.ipa
