- name: 🔑 Fetch signing files (automatic)
  script: |
    set -euxo pipefail
    test -n "${APP_STORE_CONNECT_KEY_IDENTIFIER}"
    test -n "${APP_STORE_CONNECT_ISSUER_ID}"
    test -n "${APP_STORE_CONNECT_PRIVATE_KEY}"
    test -n "${CERTIFICATE_PRIVATE_KEY}"   # <— NEU: prüfen, dass Key da ist

    keychain initialize

    if [ "$EXPORT_METHOD" = "ad-hoc" ]; then
      SIGNING_TYPE="IOS_APP_ADHOC"
    else
      SIGNING_TYPE="IOS_APP_STORE"
    fi

    app-store-connect fetch-signing-files \
      --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
      --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
      --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
      --certificate-key "$CERTIFICATE_PRIVATE_KEY" \   # <— NEU: Private Key übergeben
      --type "$SIGNING_TYPE" \
      --create \
      "$BUNDLE_ID"

    keychain add-certificates
    xcode-project use-profiles
