name: soleco_wrapper
description: iOS WebView Wrapper mit Cookie-Persistenz + Auto-Login + Sofortladen
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_inappwebview: ^6.0.0   # wichtig für Cookies
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
