name: soleco_wrapper
description: iOS WebView Wrapper mit Auto-Login & Cookie-Persistenz
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  webview_cookie_manager: ^2.0.6   # <— NEU

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
