name: soleco_wrapper
description: iOS WebView Wrapper mit Auto-Login, Cookie-Persistenz und Schnellstart-Button
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # WebView + Hilfen
  webview_flutter: ^4.7.0
  webview_cookie_manager: ^2.0.6
  url_launcher: ^6.3.0

  # Sicheres Speichern von Login-Daten & Cookies
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
